### ISSUE TITLE
Names to VOTE On ONLY

### ISSUE THREAD

**Issue by wblaircox** [ConfederationC/Project_2018#13]
List JUST the name you want to vote on. YES = thumbs UP NO=Thumbs DOWN. 

**No other comments allowed** and will be deleted (I hope it will let me delete)

**Comment by ScentedOrangeDEV** [comment]
DKARL

**Comment by wblaircox** [comment]
Kaukinen Advanced Laboratories

**Comment by TannerVT** [comment]
DKAL (Daniel Kaukinen Advanced Laboratories)

**Comment by Cigaretteman** [comment]
Dkal

**Comment by ByounghyunOh** [comment]
DKAL

**Comment by sdavenpoNorbert** [comment]
DKAL.

**Comment by KaukinenConfed** [comment]
Use the thumbs up
do not retype them in

**Comment by ESaarimaki** [comment]
Confederation Active Laboratories

**Comment by MikeScott97** [comment]
Ontario Sustainability and Fitness Center

**Comment by tander24** [comment]
Advanced Laboratories : The Daniel Experience

**Comment by KaukinenConfed** [comment]
I guess we will run with DKAL then
