### ISSUE TITLE
New company name

### ISSUE THREAD

**Issue by sdavenpoNorbert** [ConfederationC/Project_2018#2]
The name "Ontario Business 77463728" is a boring name. We need to come up with something better. I'm personally not great at naming things, but since this is a research and development company, maybe something like "R&D" (Research and Development), or maybe the name should be relevant to what we are actually researching. If we're researching astronomy, it could be something like "Researching the Stars." It should be a fun-sounding name, and not something boring or dull, but not something overly long, because it has to be a name that sticks in people's heads.

**Comment by TannerVT** [comment]
I say the name "Kaukinen Advanced Laboratories", which I totally came up with, and didn't steal from another thread from anyone named Matt.

**Comment by sdavenpoNorbert** [comment]
@TannerVT Yes!

**Comment by MikeScott97** [comment]
I agree the name should be changed, because of the R&D focuses on sustainable energy, and there are fitness facilities, such as the fitness center and the diving club I suggest we name the company "Ontario Sustainability and Fitness Center"

**Comment by Mamodeo** [comment]
Tanner has an amazing idea that he came up with and fully support his decision.

**Comment by AmirGoriya** [comment]
I would like to propose a small alteration. Instead of "Kaukinen", we can say "DK". Could be Daniel Kaukinen, could be Donkey Kong. Who knows?

**Comment by KaukinenConfed** [comment]
From Mamodeo on the other thread
That could work, I was thinking more tongue-in-cheek like "Kaukinen Advanced Laboratories"Also, I believe he said only create one issue thread?

**Comment by SilentSword047** [comment]
Maybe we should decide on what our facility will be first.

**Comment by sdavenpoNorbert** [comment]
How about "DK Advanced Sustainability and Fitness Center Laboratories?" Or is that too long?

**Comment by KaukinenConfed** [comment]
The facility is ALL of that document... Go Big!

**Comment by SilentSword047** [comment]
Oh ok!

**Comment by ScentedOrangeDEV** [comment]
How about "Research"?

**Comment by TannerVT** [comment]
Let's go even shorter and go DKAL - pronounced like "decal", but stands for Daniel Kaukinen Advanced Laboratories"

**Comment by sdavenpoNorbert** [comment]
YES! I say we do DKAL! DKAL DKAL DKAL! It's perfect!

**Comment by SilentSword047** [comment]
I upvote "Daniel Kaukinen Advanced Laboratories"

**Comment by TannerVT** [comment]
We good for DKAL?

**Comment by MikeScott97** [comment]
That is a good suggestion

**Comment by Cigaretteman** [comment]
It caught my eye when I saw "Kaukinen Advanced Laboratories", I think that "Kaukinen Advanced Laboratories" is a great name. I hope that "Kaukinen Advanced Laboratories" will lead the company as a representation and become a house hold name.

**Comment by dalessard** [comment]
I also like DKAL

**Comment by ScentedOrangeDEV** [comment]
DKARL?

**Comment by sdavenpoNorbert** [comment]
ScentedOrangeDEV What? "Research?" That's a boring name! And it's not "DKARL!"

**Comment by ESaarimaki** [comment]
What about Kaukinen Advanced Active Laboratories?

**Comment by wblaircox** [comment]
> I say the name "Kaukinen Advanced Laboratories", which I totally came up with, and didn't steal from another thread from anyone named Matt.

KALCorp

**Comment by AmirGoriya** [comment]
Again, the facility is _not_ just for R&D.

**Comment by sdavenpoNorbert** [comment]
Blair, you're a hypocrite. Stealing is one thing but stealing from a stealer? That's double-y wrong!

**Comment by ScentedOrangeDEV** [comment]
<b> I prefer DKARL </b>

**Comment by TannerVT** [comment]
A laboratory does not mean just research, at least in my head

**Comment by Mamodeo** [comment]
I support Amir's decision for DKAL

**Comment by ESaarimaki** [comment]
DKAL is a good idea, really catchy.

**Comment by sdavenpoNorbert** [comment]
DKARL (Hotline bling meme picture of Drake pushing it away)
DKAL (Hotline bling meme picture of Drake looking happy)

**Comment by Cigaretteman** [comment]
This is a safe space, no harassment @sdavenpoNorbert

**Comment by MikeScott97** [comment]
We need 3 final names

**Comment by sdavenpoNorbert** [comment]
Commandment #11: Thou shalt not harrass

**Comment by wblaircox** [comment]
> Blair, you're a hypocrite. Stealing is one thing but stealing from a stealer? That's double-y wrong!

LOL, usually these don't fill up with replies over 5 minutes with no time to read and reply. Whoever made KAL - I like it :D

**Comment by TannerVT** [comment]
It seems like DKAL is widely supported at this point.

**Comment by dalessard** [comment]
DK said 3 names brought forward

**Comment by SilentSword047** [comment]
DKAL is my #1 choice

**Comment by Mamodeo** [comment]
Dan's Fun Space and other activities

**Comment by jmaki9** [comment]
Donkey Kong

**Comment by AmirGoriya** [comment]
Project Immolation.

**Comment by sdavenpoNorbert** [comment]
DKAL is a perfect name! I say we go with that name! If I had to pick 3 others... DK and Kaukinen Advanced Laboratories

**Comment by Cigaretteman** [comment]
Can we agree on DKAL and move on to #2

**Comment by MikeScott97** [comment]
3 names agreed upon by everyone

**Comment by sdavenpoNorbert** [comment]
Is there any way to mute words in this? I want to mute the words "DKARL" and "Donkey Kong."

**Comment by ScentedOrangeDEV** [comment]
Black Mesa Research Lab

**Comment by ScentedOrangeDEV** [comment]
> Is there any way to mute words in this? I want to mute the words "DKARL" and "Donkey Kong."

No

**Comment by SilentSword047** [comment]
Black Mesa Research Lab should be #2

**Comment by ESaarimaki** [comment]
Confederation Advanced Laboratories

**Comment by wblaircox** [comment]
Thought this had a voting system at one time for rating issues...

**Comment by sdavenpoNorbert** [comment]
What the hell even is "Mesa?"

**Comment by sdavenpoNorbert** [comment]
What even is "Mesa?"

**Comment by Cigaretteman** [comment]
Guys lets decide here, you can add your own suggestions and vote https://poll.ly/#/2qy7N0N9/2NprdbJg

**Comment by MikeScott97** [comment]
Daniel's R&D Swim Team Club Facility

**Comment by AmirGoriya** [comment]
> Thought this had a voting system at one time for rating issues...

That would be useful.

**Comment by ScentedOrangeDEV** [comment]
Its a reference from a video game us civilized people play

**Comment by sdavenpoNorbert** [comment]
You elitist!

**Comment by wblaircox** [comment]
Welll there is the votes... write each one here, separately - thumb up

**Comment by sdavenpoNorbert** [comment]
**_THIS COMMENT SAYS NOTHING MEANINGFUL I JUST WANTED TO GRAB YOUR ATTENTION_**

**Comment by wblaircox** [comment]
> **_THIS COMMENT SAYS NOTHING MEANINGFUL I JUST WANTED TO GRAB YOUR ATTENTION_**

is that Dan?

**Comment by AmirGoriya** [comment]
> > **_THIS COMMENT SAYS NOTHING MEANINGFUL I JUST WANTED TO GRAB YOUR ATTENTION_**
> 
> is that Dan?

That would be Simeon.

**Comment by Cigaretteman** [comment]
Vote so we can come to a real conclusion https://poll.ly/#/2qy7N0N9/2NprdbJg

**Comment by wblaircox** [comment]
Pretty sure by taking this into the separate voting system, we've negated the purpose of this.

**Comment by sdavenpoNorbert** [comment]
I say we go with the most perfectest name ever: Norbert's Laboratory and Research DK Mesa Thingy

**Comment by MikeScott97** [comment]
thats what i was thinking blair

**Comment by Cigaretteman** [comment]
We became the senate, start voting or you dont have a voice

**Comment by AmirGoriya** [comment]
> Pretty sure by taking this into the separate voting system, we've negated the purpose of this.

Agreed.

**Comment by AmirGoriya** [comment]
I vote DKAL.

**Comment by wblaircox** [comment]
**So do this someone - list each one here,  separate post. Then everyone Thumb up you choice**

**Comment by Liveey** [comment]
Kaitlyn Dennison

Initial D, Deja Vu

**Comment by jdecoppi** [comment]
Haha DKAL, love it. But I do quite enjoy Black Mesa :)

**Comment by wblaircox** [comment]
No other comments, keep this clear

**Comment by AmirGoriya** [comment]
> t each one here, separate post. Then everyone Thumb up you choice

I like that idea.

**Comment by sdavenpoNorbert** [comment]
Black Mesa is overrated.

**Comment by SilentSword047** [comment]
DKAL

**Comment by TannerVT** [comment]
I'm going with DKAL

**Comment by Liveey** [comment]
DKAL is fine

**Comment by MikeScott97** [comment]
we already decided on DKAL, we need 3

**Comment by ByounghyunOh** [comment]
DKAL some reason keep remind me North Korea (DPRK, PRK, DPR), maybe only Korea things ^^;
But, I'm voting to DKAL.

**Comment by SilentSword047** [comment]
Black Mesa

**Comment by sdavenpoNorbert** [comment]
Yeah, I'm okay with DKAL. 'Slong as it's not DKARL.

**Comment by Liveey** [comment]
I like DKARL now

**Comment by wblaircox** [comment]
hey, posting on Discord, stop posting here for a moment

**Comment by sdavenpoNorbert** [comment]
How about DKABML? Daniel Kaukinen Advanced Black Mesa Laboratories?

**Comment by MikeScott97** [comment]
were not supposed to use discord

**Comment by jmaki9** [comment]
Shoulda went with DPRK

**Comment by sdavenpoNorbert** [comment]
@wblaircox Why is there a "W" at the beginning of your name?

**Comment by sdavenpoNorbert** [comment]
@MikeScott97 *We're

**Comment by Cigaretteman** [comment]
https://www.google.ca/url?sa=i&source=images&cd=&ved=2ahUKEwj7heiJ7dHeAhVl34MKHWpqDU4QjRx6BAgBEAQ&url=https%3A%2F%2Fwww.harpercollins.com%2Fauthors%2Fsteveharvey%2F&psig=AOvVaw2WnKBAGxnntggIxPoVLqOd&ust=1542215096070645

**Comment by TannerVT** [comment]
**OK, LISTEN UP**

Do a thumbs up for DKAL
Do a laugh for DKARL
Do a heart for Black Mesa

**Comment by ScentedOrangeDEV** [comment]
DKARL is all I could actually come up with

**Comment by Cigaretteman** [comment]
![image](https://user-images.githubusercontent.com/45010504/48430061-70200200-e73c-11e8-89c8-2012b3274c2c.png)

**Comment by Mamodeo** [comment]
That picture is so obnoxiously big, jesus

**Comment by sdavenpoNorbert** [comment]
![2017-08-25](https://user-images.githubusercontent.com/44812703/48430134-93e34800-e73c-11e8-8cef-6c07fe300594.png)

**Comment by wblaircox** [comment]
ugh, can we be done now.

**Comment by jdecoppi** [comment]
It's amazing

**Comment by sdavenpoNorbert** [comment]
DKAL is the name.

**Comment by AmirGoriya** [comment]
We need three names though.

**Comment by jdecoppi** [comment]
I do really like DKAL, and enjoy Black Mesa as a second.

**Comment by SilentSword047** [comment]
Well we have 3 top choices from the poll

**Comment by jmaki9** [comment]
DKAL was the first, Black Mesa was the second, and I forget the third one

**Comment by SilentSword047** [comment]
Can we just go with those?

**Comment by AmirGoriya** [comment]
How about we go with DKAL, Black Mesa, and CAL as our options?

**Comment by ESaarimaki** [comment]
Yes

**Comment by jdecoppi** [comment]
Agreed with CAL, I think DKARL is too similar to DKAL

**Comment by Mamodeo** [comment]
I agree with Amir's statement

**Comment by Liveey** [comment]
DKAL, Black Mesa, CAL

**Comment by Cigaretteman** [comment]
I am voting for DKAL, Blackmesa, and Confederation Active Laboratories

**Comment by sdavenpoNorbert** [comment]
Thumbs up for DKAL, Hooray for DKARL, Heart for Black Mesa, Thumbs down for Confederation Active Laboratories, Confused for Steve Harvey

**Comment by wblaircox** [comment]
To clean this up - opened a new issue - go look

**Comment by ByounghyunOh** [comment]
Go with DKAL, Black Mesa, CAL

**Comment by KaukinenConfed** [comment]
Please do the vote on The second thread

**Comment by KaukinenConfed** [comment]
switched threads. This one is going a little off course
