### ISSUE TITLE
Website Delegation

### ISSUE THREAD

**Issue by jdecoppi** [ConfederationC/Project_2018#30]
Cafeteria - Joe
Advertising - Jacob
R&D - Michael
Hydro/aquaponics - Domenico
Recreation - Erik
Fitness Center - Joe
Energy Systems - Erik

These to be evenly distributed:
Index -
About - 
Contact - 

Theme - Nature, green/white
     -could also be obtained by a free bootstrap theme online, if intended to be free and credited

**Comment by jdecoppi** [comment]
My bad, not enough caffeine yet. Issue has been edited.

**Comment by ESaarimaki** [comment]
Let's not forget about the Fitness Center.

**Comment by ESaarimaki** [comment]
I can help work on the Fitness Center.

**Comment by ESaarimaki** [comment]
We'll have to evenly distribute the remaining areas of the web page across the group. Is there any other areas some of you would like to do? I wouldn't mind helping with Recreation or Energy Systems.

**Comment by MikeScott97** [comment]
I dont mind helping out with other parts of the site either

**Comment by jdecoppi** [comment]
I can take up Cafeteria and the Fitness Center.

This'll leave us with just the main pages (index, contact, about, etc.) as well as theming.

**Comment by tollis90** [comment]
I can help as well

**Comment by ESaarimaki** [comment]
I think for a website of this nature, a bright, positive theme would really suite it?

**Comment by tollis90** [comment]
lets put some green

**Comment by jdecoppi** [comment]
Nature theme sounds great, agreed with the green :)

**Comment by MikeScott97** [comment]
green with white or white with green accents might be nice for a theme

**Comment by ESaarimaki** [comment]
Index, Contact and About pages. @jdecoppi we can just kind of evenly distribute that. Those should be relatively straight forward.

**Comment by ESaarimaki** [comment]
Other than that, I think we're pretty well set.

**Comment by jdecoppi** [comment]
I've further edited (why do I always want to spell this with two t's) the duty list, if there's any issues or changes feel free to let me know

**Comment by MikeScott97** [comment]
this tool is good for picking complementary colour sets https://www.sessions.edu/color-calculator/, we should utilize it

**Comment by ESaarimaki** [comment]
@jdecoppi where is the duty list?

**Comment by jdecoppi** [comment]
We could also acquire a free bootstrap theme online, assuming it's intended to be free and we credit it :)

**Comment by ESaarimaki** [comment]
Sounds good. Joe, can you add this information to the document?

**Comment by jdecoppi** [comment]
I further updated the theme section on the initial post.

That said, the issue of determining our tasks is concluded, and as such I will be closing the issue.
