### ISSUE TITLE
Planning tasks about Energy Docs Project

### ISSUE THREAD

**Issue by ByounghyunOh** [ConfederationC/Project_2018#33]
- [x] Deciding the subject
- [x] Deciding the project role
- [x] Deciding the commuincation Tool

**Comment by ByounghyunOh** [comment]
Riley, I like your topic idea that Alternate Energy

**Comment by R-Y-M-R** [comment]
Right. I see you have created the EnergySystems branch for us to use! Thanks.

@ByounghyunOh Do you have any specific ideas for alternative energy? I don't, but will research some now.

**Comment by R-Y-M-R** [comment]
I've created my own branch [EnergySystemsRiley](https://github.com/ConfederationC/Project_2018/tree/EnergySystemsRiley) (per today's lab instructions).

Regarding project roles, I have researched some [alternative energy sources](https://www.renewableresourcescoalition.org/alternative-energy-sources/) and would like to use one of these 3:

1. Solar
2. Hydroelectric 
3. Wind

Do you have a preference or input @ByounghyunOh ?

Communication Tools:
Discord? I sent a friend request to you.

**Comment by R-Y-M-R** [comment]
[Trello](https://trello.com/) is a good collaboration tool I've used in the past too!

**Comment by ByounghyunOh** [comment]
1. Solar will be the best choice. Because it is most common and widely uses

Communication tool : we have to use github project, trello may too much overlab. We just need to simple communication methods. Let’s stick with discord
