### ISSUE TITLE
Energy System Docs

### ISSUE THREAD

**Issue by ByounghyunOh** [ConfederationC/Project_2018#46]
- [x] Solar Energy : Byounghyun -> [Document Link](https://github.com/ConfederationC/Project_2018/blob/EnergySystems/README.md)
- [x] Wind farm : Riley -> [Document Link](https://github.com/ConfederationC/Project_2018/tree/EnergySystemsRiley)

**Comment by ByounghyunOh** [comment]
Solar Energy Document Done, you can add your document in MD file.
When I submit the document in Blackboard, I will put in document link.

**Comment by R-Y-M-R** [comment]
Nice job! I will post here when mine is ready.

**Comment by R-Y-M-R** [comment]
While not complete, here's my [progress](https://github.com/ConfederationC/Project_2018/blob/EnergySystemsRiley/README.md) after an hour.

**Comment by ByounghyunOh** [comment]
I just clarified with Daniel about the using MD file format, we good to go. We do not need to change to html, rtf, and txt file format. Only one thing he mentioned that we should editing MD document in the local, not rely on in GitHub editor.

**Comment by ByounghyunOh** [comment]
When your document is done, can you quickly check the grammar and spelling mistake in my research document?

**Comment by R-Y-M-R** [comment]
Yes, I will!

**Comment by ByounghyunOh** [comment]
We All done
