### ISSUE TITLE
Recreational Information

### ISSUE THREAD

**Issue by ESaarimaki** [ConfederationC/Project_2018#52]
@jmaki9 @gsuresh9798 @nsultana7 
I have started the Recreational page development, and I was just curious to what your group has come up with and ways I can find and corporate your work into the Recreational web page.

**Comment by ESaarimaki** [comment]
![image](https://user-images.githubusercontent.com/44812698/49611730-72a6fd80-f970-11e8-83bf-e9b8d1630e9a.png)
This is currently what I have started on the web page.

**Comment by jmaki9** [comment]
So far we haven't begun work on the website yet but we are ready to. Once
we get started I'll let you know what we include.

**Comment by jmaki9** [comment]
I think you might want to ask Erik. He told me that he's going to be doing
the website for Recreation so he'll know how to handle the content.

Joshua

**Comment by gsuresh9798** [comment]
Hey Erik,

I am planning to create the .md file and the webpage and push it to my branch named gsuresh. I am starting to work on my .md file.


________________________________

**Comment by ESaarimaki** [comment]
@nsultana7 All I need to know is what branch you are working in and I can grab the information from there.
@gsuresh9798 Thank you, I will check it out.

**Comment by gsuresh9798** [comment]
Hello Erik

I have included my content in the Readme.md file, in the gsuresh branch.

________________________________

**Comment by nsultana7** [comment]
hi Erik
I included my 1 html file and 2 images in nsultana branch

**Comment by ESaarimaki** [comment]
Thank you both very much! I will work on incorporating your work into the webpages. @gsuresh9798 @nsultana7
