### ISSUE TITLE
Energy Systems Information

### ISSUE THREAD

**Issue by ESaarimaki** [ConfederationC/Project_2018#53]
@ByounghyunOh @R-Y-M-R 
I am beginning the development of the Energy Systems web page. I was curious as to what information you have decided upon regarding Energy Systems and as to where this information is kept, so it can be incorporated into the web page.

**Comment by ByounghyunOh** [comment]
We' 've been working on Solar power and Wind farms.
You can check [Riley's branch](https://github.com/ConfederationC/Project_2018/tree/EnergySystemsRiley).
Riley is still working on it, so he will update some contents soon.

**Comment by R-Y-M-R** [comment]
Hey Erick, I would recommend you start with @ByounghyunOh 's branch ([EnergySystems](https://github.com/ConfederationC/Project_2018/tree/EnergySystems)).
I will complete mine today.

**Comment by R-Y-M-R** [comment]
@ESaarimaki, you should be able to integrate the information contained in [EnergySystemsRiley](https://github.com/ConfederationC/Project_2018/tree/EnergySystemsRiley) branch's [README.md](https://github.com/ConfederationC/Project_2018/blob/EnergySystemsRiley/README.md) ([raw](https://raw.githubusercontent.com/ConfederationC/Project_2018/EnergySystemsRiley/README.md)). If you view that branch, you will be able to see the documentation/data and resource we've compiled.

**Comment by ByounghyunOh** [comment]
We all ready to go, you can use any of branch from ours
