### ISSUE TITLE
Rosylyn compiler error: Cant compile due to compiler not found. 

### ISSUE THREAD

**Issue by ScentedOrangeDEV** [ConfederationC/Project_2018#86]
The issue seems to only be reproducible by me no matter how i pull the source from the repo. I am unable to use the C# compiler to view the website (somehow Microsoft's Rosylyn is more picky then Javas Jack compiler...) To get around this im using VS and making my commits on the asp files through github website. If anyone else had compiler errors (as in it cant find the compiler...) please let me know

**Comment by tollis90** [comment]
I had the same problem a few days ago. What I did is: 
- Open VS
- Go in Team Explorer and click on Sync
- Set Default as a start page
- Try to run (if you still have the same problem close VS and re-open)
Hope it works

**Comment by ScentedOrangeDEV** [comment]
Yeah I tried all that already. Oh well

**Comment by tollis90** [comment]
try to clone the project on another folder. Make sure you don't use too many subfolders. Just put it on the desktop

**Comment by tollis90** [comment]
I fixed your problem. You had an opening tag missing
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
